### ISSUE TITLE
Link is not updating correctly

### ISSUE THREAD

**Issue by l174rd** [svewap/ws_flexslider#18]
In TYPO3 v7.6 there's a bug while I try to update the link of the image in Flexslider.

This is the file where that field is defined:
`typo3conf/ext/ws_flexslider/Configuration/TCA/Image.php`

and in this line (188) is possibly the error:
`'softref' => 'typolink[linkList]',`

should be:
`'softref' => 'typolink,typolink_tag,images,url',`

The problem, while selecting the link from a page the **hidden field is not being updated**. Saving the page **doesn't update** the ID correctly (there's still the old value).

If I enter the ID **manually** in the input field it is being saved correctly, because the hidden field is being updated. Why is this happening? Can anyone reproduce this?

![typo3_bug_flexslider_link](https://cloud.githubusercontent.com/assets/806113/18677601/8dde1144-7f59-11e6-9340-9315ce6a0a7e.jpg)

**Comment by l174rd** [comment]
Any ideas or patches for this problem? @svewap

**Comment by svewap** [comment]
I updated the code. This works for me. Can you please test it again?

**Comment by l174rd** [comment]
Thank you! It work's now like a charm.
