### ISSUE TITLE
No Page cache

### ISSUE THREAD

**Issue by horizons2** [svewap/ws_flexslider#2]
Hi,
We are using the ws_flexslider extension on one page.
We are using the extension nc_staticfilecache and the cache is generated normally for every page.
Except the ones with the ws_flexslider.

We got this "error" from the nc_staticfilecache extension
page has INTincScript:
tx_extbase_core_bootstrap->run

I guess it has something to do that the extension is preventing the generation of cache because of beeing a USER_INT object?

Is there anything how I could solve this issue?
best regards

**Comment by j4k3** [comment]
Same problem here...

**Comment by j4k3** [comment]
Tried horizons2 tip and it seems to work fine. Quite a bummer that this issue is still not fixed after a full year, as this problem literally kills all caching on every page this Extension is displayed on.

**Comment by svewap** [comment]
In the newest version 1.3.1 this problem is already fixed.
