### ISSUE TITLE
Icon Fonts are not loading in TER-Version 1.5.7 of the Extension

### ISSUE THREAD

**Issue by m10a** [svewap/ws_flexslider#41]
TYPO3-ter version 1.5.7 comes with CSS of jQuery FlexSlider v2.7.1 which has no declarations for font-icons in flexslider.css, i.e. the fonts in the font dir are not loaded. The Version here on github and the one on packagist comes with the older CSS from FlexSlider v2.2.0, which loads the fonts. 

In the original Version of the jQuery FlexSlider, which is offered here https://woocommerce.com/flexslider/ the declaration for the font integration are located in the demo.css. In v2.7.0 they are still in flexslider.css

**Comment by rteitge** [comment]
Still in 1.5.9.

**Comment by svewap** [comment]
fixed
