### ISSUE TITLE
jquery is very old

### ISSUE THREAD

**Issue by herzogkienast** [svewap/ws_flexslider#44]
Hey Sven,

Standard jquery in the extension is 1.7.2 which is very old and shows an error in chorme.
I played around with jquery and the last version that works ist 1.8.2

[globalVar = LIT:1 = {$plugin.tx_wsflexslider.includejquerycore}]
page.includeJSFooterlibs {
	#jquery = http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js
	#jquery = http://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js
	jquery = http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js
	jquery.external = 1
	jquery.forceOnTop = 1
}
[global]

All higher versions will make some problems - in espacially in mobile versionsof the website, for example take a look at chrome.

I am using TYPO3 8 and 1.5.9 of the slider.

Cheers,
Andrea

**Comment by MrManga** [comment]
Furthermore it is not described to activate jquery in the Constant-Editor (well for me I had to do this before getting this plugin getting to work.)
A hint in the documentation would be helpful :)

**Comment by svewap** [comment]
Fixed in 28b0714fd342901e30ba98d04bb692e493bb7a92
