### ISSUE TITLE
Unknown type: select, render type: select with TYPO3 10 LTS/ws_flexslider 1.5.12

### ISSUE THREAD

**Issue by wini2** [svewap/ws_flexslider#47]
Hello,

most fields on 'Erweiterungsoptionen' show errors - 'Unknown type: select, render type: select'.

Tested on two fresh TYPO3 104 (LTS)-Installations with PHP  7.3.11.

Check TCA Migarations shows up "The 'tx_wsflexslider_domain_model_image' TCA configuration 'showRecordFieldList' inside the section 'interface' is not evaluated anymore and should therefore be removed".

Best regards
wini2

**Comment by svewap** [comment]
Fixed. The showRecordFieldList field is still inside because of downgrade compatibility.
