### ISSUE TITLE
Version 1.5.13 breaks in TYPO3 9.5 because extbase domain mapping is missing

### ISSUE THREAD

**Issue by bfzgaier** [svewap/ws_flexslider#48]
Dropping extbase domain mapping with https://github.com/svewap/ws_flexslider/commit/8db786eddeeb44796c18f7c77d64028b57a330fc breaks in TYPO3 9.5.

    config.tx_extbase.persistence.classes {
        WapplerSystems\WsFlexslider\Domain\Model\Content {
            mapping {
                tableName = tt_content
            }
        }
    }

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/10.0/Breaking-87623-ReplaceConfigpersistenceclassesTyposcriptConfiguration.html

**Comment by svewap** [comment]
Thanks. Fixed in commit 6091fdc8eb5ca6cfa9f249165dd191d695e42096
